image: $CI_REGISTRY/baikal-m/spi_builder:1.0

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.build_firmware_template: &build_firmware_dfn
  stage: build
  script:
    - make BOARD=${BOARD} MAX_FREQ=${MAX_FREQ} ARMTF_DEBUG=${ARMTF_DEBUG} UEFI_DEBUG=${UEFI_DEBUG}
    - |
      BRANCH=""
      if [ "$CI_COMMIT_BRANCH" != "$CI_DEFAULT_BRANCH" ]; then
        if [ -n "${CI_COMMIT_BRANCH}" ]; then
          BRANCH="${CI_COMMIT_BRANCH}_"
        fi
      fi
      VERSION=$(git describe --tags)
      [ ${ARMTF_DEBUG} -eq 1 ] && VERSION=${VERSION}-armtfdbg
      [ ${UEFI_DEBUG} -eq 1 ] && VERSION=${VERSION}-uefidbg
      echo "Uploading version ${VERSION}"
      echo "          branch ${BRANCH}"
      echo "          board ${BOARD}"
      GIT_TAG=$(git describe --tags --no-abbrev)
      FULL_PATH="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${GIT_TAG}/${BRANCH}${BOARD}_${VERSION}"
      echo "Full path: ${FULL_PATH}"
      tar cf - -C release/${BOARD} . | xz -z9 -T0 -c - | curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file - ${FULL_PATH}.images.tar.gz

et151-mb-1.1-rev1:
  variables:
    BOARD: et151
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et101-mb-1.2-rev2:
  variables:
    BOARD: et101-v2-dp
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et101-mb-1.1-rev2:
  variables:
    BOARD: et101-v2-lvds
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et101-mb-1.1-rev1.1:
  variables:
    BOARD: et101-lvds
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

tf307-mb-s-d-rev4.0:
  variables:
    BOARD: mitx-d
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

em407-com-express:
  variables:
    BOARD: em407
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et111-laptop:
  variables:
    BOARD: et111
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et113-mb-a-server:
  variables:
    BOARD: et113
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

et141-ramac-2x-pcie-dtx:
  variables:
    BOARD: et141
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
    MAX_FREQ: 2400
  <<: *build_firmware_dfn

