image: $CI_REGISTRY/elpitech/lpt/containers/mc-builder:0-0-3

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_UPDATE_FLAGS: --jobs 8

.build_firmware_template: &build_firmware_dfn
  stage: build
  tags:
    - kubernetes-mid
  script:
    - make BOARD=${BUILD_TARGET} ARMTF_DEBUG=${ARMTF_DEBUG} UEFI_DEBUG=${UEFI_DEBUG}
    - |
      VERSION=$(git describe --tags)
      [ ${ARMTF_DEBUG} -eq 1 ] && VERSION=${VERSION}-armtfdbg
      [ ${UEFI_DEBUG} -eq 1 ] && VERSION=${VERSION}-uefidbg
      echo "Uploading version ${VERSION}"
      echo "          branch ${CI_COMMIT_BRANCH}"
      echo "          board ${BOARD_NAME}"
      GIT_TAG=$(git describe --tags --no-abbrev)
      FULL_PATH="${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/firmware/${GIT_TAG}/${BOARD_NAME}_${CI_COMMIT_BRANCH}_${VERSION}"
      echo "Full path: ${FULL_PATH}"
      tar cf - -C release/${BUILD_TARGET} . | xz -z9 -T0 -c - | curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file - ${FULL_PATH}.images.tar.xz

et151-mb-2-rev1:
  variables:
    BOARD_NAME: ET151-MB-2-Rev1
    BUILD_TARGET: et151-dp
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et151-mb-1.1:
  variables:
    BOARD_NAME: ET151-MB-1.1
    BUILD_TARGET: et151-lvds
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et101-mb-1.2-rev2:
  variables:
    BOARD_NAME: ET101-MB-1.2-Rev2
    BUILD_TARGET: et101-v2-dp
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et101-mb-1.1-rev2:
  variables:
    BOARD_NAME: ET101-MB-1.1-Rev2
    BUILD_TARGET: et101-v2-lvds
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

tf307-mb-s-d-rev4.0:
  variables:
    BOARD_NAME: TF307-MB-S-D-Rev4.0
    BUILD_TARGET: mitx-d
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

em407-com-express:
  variables:
    BOARD_NAME: EM407
    BUILD_TARGET: em407
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et111-mb-rev1.0:
  variables:
    BOARD_NAME: ET111-MB-Rev1.0
    BUILD_TARGET: et111
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et113-mb-a-server:
  variables:
    BOARD_NAME: ET113-MB-A
    BUILD_TARGET: et113
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et121-mb-rev1:
  variables:
    BOARD_NAME: ET121-MB-Rev1
    BUILD_TARGET: et121
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et141-mb-rev1:
  variables:
    BOARD_NAME: ET141-MB-Rev1
    BUILD_TARGET: et141
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et161-mb:
  variables:
    BOARD_NAME: ET161
    BUILD_TARGET: et161
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

et143-mb-server:
  variables:
    BOARD_NAME: ET143-MB
    BUILD_TARGET: et143
    ARMTF_DEBUG: 0
    UEFI_DEBUG: 0
  <<: *build_firmware_dfn

